"""Initial tables

Revision ID: 41c683a4e8bc
Revises: 
Create Date: 2026-01-23 00:06:54.358348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c683a4e8bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='channel_status'), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('processed_video_count', sa.Integer(), nullable=True),
    sa.Column('time_range_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_channel_id')
    )
    op.create_index('idx_channel_created_at', 'channels', ['created_at'], unique=False)
    op.create_index('idx_channel_status', 'channels', ['status'], unique=False)
    op.create_table('stocks',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.Enum('NYSE', 'NASDAQ', name='stock_exchange'), nullable=False),
    sa.Column('last_price', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index('idx_stock_exchange', 'stocks', ['exchange'], unique=False)
    op.create_table('processing_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('log_level', sa.Enum('info', 'warning', 'error', name='log_level'), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_channel_created', 'processing_logs', ['channel_id', 'created_at'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=False),
    sa.Column('transcript_status', sa.Enum('pending', 'fetched', 'failed', name='transcript_status'), nullable=True),
    sa.Column('analysis_status', sa.Enum('pending', 'completed', 'failed', name='analysis_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_video_id')
    )
    op.create_index('idx_video_channel_id', 'videos', ['channel_id'], unique=False)
    op.create_index('idx_video_published_at', 'videos', ['published_at'], unique=False)
    op.create_table('stock_mentions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('sentiment', sa.Enum('buy', 'hold', 'sell', 'mentioned', name='sentiment_type'), nullable=False),
    sa.Column('price_at_mention', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mention_ticker', 'stock_mentions', ['ticker'], unique=False)
    op.create_index('idx_mention_video_id', 'stock_mentions', ['video_id'], unique=False)
    op.create_index('unique_video_ticker', 'stock_mentions', ['video_id', 'ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_video_ticker', table_name='stock_mentions')
    op.drop_index('idx_mention_video_id', table_name='stock_mentions')
    op.drop_index('idx_mention_ticker', table_name='stock_mentions')
    op.drop_table('stock_mentions')
    op.drop_index('idx_video_published_at', table_name='videos')
    op.drop_index('idx_video_channel_id', table_name='videos')
    op.drop_table('videos')
    op.drop_index('idx_log_channel_created', table_name='processing_logs')
    op.drop_table('processing_logs')
    op.drop_index('idx_stock_exchange', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index('idx_channel_status', table_name='channels')
    op.drop_index('idx_channel_created_at', table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
